version: '3'
services:
  app:
    container_name: unique-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    depends_on:
      - database
    volumes:
      - mongo-volume:/app
  database:
    container_name: unique-database
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
volumes:
  mongo-volume:
